ePizza.UI/Models/ProductTypes/ProductTypeAddViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ePizza.UI.Models.ProductTypes
{
    public class ProductTypeAddViewModel : BaseViewModel
    {
        [Required(ErrorMessage = "İsim alanı boş olamaz")]
        public string Name { get; set; }
    }
}

ePizza.UI/Models/ProductTypes/ProductTypeListViewModel.cs
using ePizza.Entities.Dtos.ProductTypes;
using System.Collections.Generic;

namespace ePizza.UI.Models.ProductTypes
{
    public class ProductTypeListViewModel : BaseViewModel
    {
        public ProductTypeListDto ProductTypeListDto { get; set; }
    }
}

ePizza.UI/Models/ProductTypes/ProductTypeUpdateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ePizza.UI.Models.ProductTypes
{
    public class ProductTypeUpdateViewModel : BaseViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "İsim alanı boş olamaz")]
        public string Name { get; set; }
    }
}

ePizza.UI/Models/ProductTypes/ProductTypeViewModel.cs
using ePizza.Entities.Dtos.ProductTypes;

namespace ePizza.UI.Models.ProductTypes
{
    public class ProductTypeViewModel
    {
        public ProductTypeDto ProductTypeDto { get; set; }
    }
}

ePizza.UI/Areas/Admin/Controllers/ProductTypesController.cs
using ePizza.Entities.Dtos.ProductTypes;
using ePizza.Services.Interfaces;
using ePizza.Shared.Utilities.Results.ComplexType;
using ePizza.UI.Interfaces;
using ePizza.UI.Models.Categories;
using ePizza.UI.Models.ProductTypes;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ePizza.UI.Areas.Admin.Controllers
{
    public class ProductTypesController : BaseController
    {
        private readonly IProductTypeService _productTypeService;

        public ProductTypesController(IUserAccessor userAccessor, IProductTypeService productTypeService) : base(userAccessor)
        {
            _productTypeService = productTypeService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAllProductTypes()
        {
            var result = await _productTypeService.GetAllAsync();

            var productType = new ProductTypeListViewModel
            {
                ProductTypeListDto = result.Data,
            };

            if (result.ResultStatus == ResultStatus.Success)
            {
                return View(productType);
            }
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(ProductTypeAddViewModel productTypeAddViewModel)
        {
            if (ModelState.IsValid)
            {
                var productType = new ProductTypeAddDto
                {
                    Name = productTypeAddViewModel.Name
                };

                var result = await _productTypeService.AddAsync(productType);
                productTypeAddViewModel.Message = result.Message;

                if (result.ResultStatus == ResultStatus.Success)
                {
                    ViewBag.ProductTypeResultMessage = result.Message;
                    return RedirectToAction("GetAllProductTypes");
                }
                ViewBag.ProductTypeResultMessage = result.Message;
                return View(productTypeAddViewModel);
            }
            return View(productTypeAddViewModel);
        }


        public async Task<IActionResult> Update(int Id)
        {
            var productType = await _productTypeService.GetAsync(Id);

            var oldProductType = new ProductTypeUpdateViewModel
            {
                Id = productType.Data.ProductType.Id,
                Name = productType.Data.ProductType.Name,
                Message = productType.Message
            };
            return View(oldProductType);
        }


        [HttpPost]
        public async Task<IActionResult> Update(ProductTypeUpdateViewModel productTypeUpdateViewModel)
        {
            if (ModelState.IsValid)
            {
                var updatedProductType = new ProductTypeUpdateDto
                {
                    Id = productTypeUpdateViewModel.Id,
                    Name = productTypeUpdateViewModel.Name
                };
                var result = await _productTypeService.UpdateAsync(updatedProductType);
                productTypeUpdateViewModel.Message = result.Message;

                if (result.ResultStatus == ResultStatus.Success)
                {
                    ViewBag.ProductTypeResultMessage = result.Message;
                    return RedirectToAction("GetAllProductTypes");
                }
                ViewBag.ProductTypeResultMessage = result.Message;
                return View(productTypeUpdateViewModel);
            }
            return View(productTypeUpdateViewModel);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var result = await _productTypeService.DeleteAsync(Id);

            if (result.ResultStatus == ResultStatus.Success)
            {
                return RedirectToAction("GetAllProductTypes");
            }
            return View();
        }
    }
}

ePizza.UI/Areas/Admin/Views/ProductTypes/Add.cshtml
@model ProductTypeAddViewModel

@{
    ViewData["Title"] = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Add</h1>

<div class="container">
    <form asp-controller="ProductTypes" asp-action="Add" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" id="Name" type="text" class="form-control" placeholder="Ürün Tipi Adı" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button class="btn badge-primary" type="submit" value="Add">Ekle</button>
            @ViewBag.ProductTypeResultMessage

        </div>
    </form>
</div>

ePizza.UI/Areas/Admin/Views/ProductTypes/GetAllProductTypes.cshtml
@model ProductTypeListViewModel

@{
    ViewData["Title"] = "GetAllProductTypes";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>GetAllProductTypes</h1>

<div class="container">

    <div id="addButtonTable">
        <table>
            <tr>
                <td>Ürün tipi eklemek için ekle butonuna tıklayınız</td>
                <td>:</td>
                <td> <a asp-area="Admin" asp-controller="ProductTypes" asp-action="Add" id="AddButton">Ürün Tipi Ekle</a></td>
            </tr>
        </table>
    </div>

    @if (Model != null)
    {
        <div>
            <table class="table" id="ListTable">
                <thead>
                    <tr>
                        <td>Id</td>
                        <td>Ürün Tipi Adı</td>
                        <td>Güncelle</td>
                        <td>Sil</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var productType in Model.ProductTypeListDto.ProductTypes)
                    {
                        <tr>
                            <td>@productType.Id</td>
                            <td>@productType.Name</td>
                            <td><a href="/Admin/ProductTypes/Update/@productType.Id" id="ListTableButton">Güncelle</a></td>
                            <td><a href="/Admin/ProductTypes/Delete/@productType.Id" id="ListTableButton">Sil</a></td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    }
    else
    {
        <p>Hiç Veri Bulunamadı</p>
    }
</div>

ePizza.UI/Areas/Admin/Views/ProductTypes/Update.cshtml
@model ProductTypeUpdateViewModel

@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Update</h1>

<div class="container">
    <form asp-controller="ProductTypes" asp-action="Update" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" name="Id" value="@Model.Id" />
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" id="Name" type="text" class="form-control" placeholder="Ürün Tipi Adı" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button class="btn badge-primary" type="submit" value="Update" >Güncelle</button>
            @ViewBag.ProductTypeResultMessage

        </div>
    </form>
</div>